// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mvc_Project.Data;

#nullable disable

namespace Mvc_Project.Migrations
{
    [DbContext(typeof(Mvc_ProjectContext))]
    [Migration("20240822105029_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mvc_Project.Models.Aankoop", b =>
                {
                    b.Property<int>("AankoopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AankoopId"), 1L, 1);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GoedGekeurd")
                        .HasColumnType("bit");

                    b.Property<int>("NaamAanvragerId")
                        .HasColumnType("int");

                    b.Property<string>("Reden")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VakId")
                        .HasColumnType("int");

                    b.Property<bool>("Verwijderd")
                        .HasColumnType("bit");

                    b.HasKey("AankoopId");

                    b.ToTable("Aankoop", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
